# Use an official Node.js runtime as a parent image
FROM node:20-alpine

# Set the working directory in the container
WORKDIR /app/backend

# Install app dependencies
# A wildcard is used to ensure both package.json and package-lock.json are copied
COPY backend/package*.json ./

RUN npm install

# Bundle app source
COPY backend/ .

# Build the TypeScript code
RUN npm run build

# Expose the port the app runs on
EXPOSE 5000

# Run the app
CMD [ "npm", "run", "serve" ]